package reciptizer.Common.Recipe;

public class Table1 {
    public Integer TABLE1_COLUMN_ID;
    public String TABLE1_COLUMN_RECIPE;
    public String TABLE1_COLUMN_CATEGORY;
    public String TABLE1_COLUMN_KITCHEN;
    public String TABLE1_COLUMN_PREFERENCES;
    public Integer TABLE1_COLUMN_TIME;
    public Integer TABLE1_COLUMN_PORTION;
    public String TABLE1_COLUMN_IMG_FULL;
    public String TABLE1_COLUMN_IMG_TITLE;

    public Table1(Integer TABLE1_COLUMN_ID, String TABLE1_COLUMN_RECIPE,
                  String TABLE1_COLUMN_CATEGORY, String TABLE1_COLUMN_KITCHEN,
                  String TABLE1_COLUMN_PREFERENCES, Integer TABLE1_COLUMN_TIME,
                  Integer TABLE1_COLUMN_PORTION, String TABLE1_COLUMN_IMG_FULL,
                  String TABLE1_COLUMN_IMG_TITLE) {
        this.TABLE1_COLUMN_ID = TABLE1_COLUMN_ID;
        this.TABLE1_COLUMN_RECIPE = TABLE1_COLUMN_RECIPE;
        this.TABLE1_COLUMN_CATEGORY = TABLE1_COLUMN_CATEGORY;
        this.TABLE1_COLUMN_KITCHEN = TABLE1_COLUMN_KITCHEN;
        this.TABLE1_COLUMN_PREFERENCES = TABLE1_COLUMN_PREFERENCES;
        this.TABLE1_COLUMN_TIME = TABLE1_COLUMN_TIME;
        this.TABLE1_COLUMN_PORTION = TABLE1_COLUMN_PORTION;
        this.TABLE1_COLUMN_IMG_FULL = TABLE1_COLUMN_IMG_FULL;
        this.TABLE1_COLUMN_IMG_TITLE = TABLE1_COLUMN_IMG_TITLE;
    }
}